name: Build/Release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Actualizado a v4

      - name: Install Node.js
        uses: actions/setup-node@v4 # Actualizado a v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Electron App (Windows)
        run: npm run dist:win
        if: matrix.os == 'windows-latest'

      - name: Build Electron App (Linux)
        run: npm run dist:linux
        if: matrix.os == 'ubuntu-latest'

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4 # <--- ¡ESTE ES EL CAMBIO CLAVE!
        with:
          name: Tack-${{ matrix.os }}
          path: dist/*